Controllers/BikeController.cs
using Bikemvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Bikemvc.Controllers
{
    [Authorize]
    public class BikeController : Controller
    {
        BikeDbContext db = new BikeDbContext();


        public ActionResult Bikes()
        {
            return View(db.BikeInfos.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(BikeInfo BikeInfo)
        {
            if (ModelState.IsValid)
            {
                db.BikeInfos.Add(BikeInfo);
                db.SaveChanges();
                return RedirectToAction("Bikes");
            }

            return View(BikeInfo);
        }
        public ActionResult Edit(int? BikeInfoId)
        {
            if (BikeInfoId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BikeInfo BikeInfo = db.BikeInfos.Find(BikeInfoId);
            if (BikeInfo == null)
            {
                return HttpNotFound();
            }
            return View(BikeInfo);
        }
        [HttpPost]
        public ActionResult Edit(BikeInfo BikeInfo)
        {
            if (ModelState.IsValid)
            {
                var BikeIn = db.BikeInfos.Where(w => w.BikeInfoId == BikeInfo.BikeInfoId).FirstOrDefault();
                BikeIn.BikeName = BikeInfo.BikeName;
                db.SaveChanges();
                return RedirectToAction("Bikes");
            }
            return View(BikeInfo);
        }
        public ActionResult Delete(int? BikeInfoId)
        {
            try
            {
                var firstEntity = db.BikeInfos.Where(c => c.BikeInfoId == BikeInfoId).FirstOrDefault();
                db.BikeInfos.Remove(firstEntity);
                db.SaveChanges();
            }
            finally
            {

            }
            return RedirectToAction("Bikes");
        }


    }
}

Views/Bike/Bikes.cshtml
@using Bikemvc.Models
@model IList<BikeInfo>

<table class="table table-bordered table-warning">
    <thead class="table table-success">
        <tr>
            <th>BikeInfoId</th>
            <th>BikeName</th>
            <th>Delete</th>
            <th>Edit</th>
        </tr>
        </thead>
        @foreach (var v in Model)
        {
            <tr>
                <td>
                    @v.BikeInfoId
                </td>
                <td>
                    @v.BikeName
                </td>
                <td>
                    @Html.ActionLink("Delete", "Delete", "Bike", new { BikeInfoId = v.BikeInfoId }, null)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", "Bike", new { BikeInfoId = v.BikeInfoId }, null)
                </td>

            </tr>
        }


</table>

<br />
<br />
<br />
<div class="btn btn-success">
     @Html.ActionLink("Create", "Create", "Bike")
</div>

Views/Bike/Create.cshtml
@{

    //if (ViewBag.Create == true)
    {
        Html.RenderPartial("CreatePartial");
    }


}

Views/Bike/CreatePartial.cshtml
@using (Html.BeginForm("Create", "Bike"))
{<div class="form-control">
    <div style="font-weight:bolder">BikeName</div> 
    @Html.TextBox("BikeName")
    <br />
    
    <input type="submit" value="Save" class="btn btn-success" style="margin-top:1%" />
</div>
}

Views/Bike/Edit.cshtml
@using Bikemvc.Models
@model BikeInfo

@{

    //if (ViewBag.Edit == true)
    {
        Html.RenderPartial("EditPartial", Model);
    }


}

Views/Bike/EditPartial.cshtml
@using Bikemvc.Models
@model BikeInfo

@using (Html.BeginForm("Edit", "Bike"))
{
    @Html.Hidden("BikeInfoId", Model.BikeInfoId)
    <div class="form-control">
        <div style="font-weight:bolder">BikeName</div>
        @Html.TextBox("BikeName")
        <br />

        <input type="submit" value="Edit" class="btn btn-success" style="margin-top:1%" />
    </div>

}